#!/usr/bin/env python3
"""Sync Hermes tool schemas and metadata from TubeAlfred's operation manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import pprint
import sys
from typing import Any
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = "https://tubealfred.com/.well-known/tubealfred-youtube-operations.v1.json"
CONTRACT_PATH = ROOT / "contracts" / "tubealfred-youtube-operations.v1.json"
GENERATED_PATH = ROOT / "generated_operations.py"
PLUGIN_PATH = ROOT / "plugin.yaml"


def load_manifest(source: str) -> dict[str, Any]:
    if source.startswith(("http://", "https://")):
        request = Request(source, headers={"User-Agent": "tubealfred-hermes-contract-sync/1"})
        with urlopen(request, timeout=30) as response:  # nosec: operator selects source
            return json.load(response)
    return json.loads(Path(source).read_text(encoding="utf-8"))


def operations_for(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    operations = []
    for operation in manifest["operations"]:
        properties: dict[str, Any] = {}
        required = []
        for parameter in operation["parameters"]:
            schema = dict(parameter["schema"])
            if parameter.get("description") and "description" not in schema:
                schema["description"] = parameter["description"]
            properties[parameter["name"]] = schema
            if parameter["required"]:
                required.append(parameter["name"])
        operations.append({
            "id": operation["id"],
            "name": operation["clients"]["agent_tool"]["name"],
            "description": operation["description"],
            "method": operation["method"],
            "path": operation["path"],
            "parameters": {
                "type": "object",
                "properties": properties,
                "required": required,
                "additionalProperties": False,
            },
            "request_parameters": [{
                "name": parameter["name"],
                "in": parameter["in"],
                "required": parameter["required"],
                "schema": parameter["schema"],
            } for parameter in operation["parameters"]],
        })
    return operations


def render_plugin(tools: list[str]) -> str:
    text = PLUGIN_PATH.read_text(encoding="utf-8")
    prefix, _separator, remainder = text.partition("provides_tools:\n")
    if not _separator:
        raise ValueError("plugin.yaml is missing provides_tools")
    suffix_lines = remainder.splitlines()
    while suffix_lines and suffix_lines[0].startswith("  - "):
        suffix_lines.pop(0)
    rendered = prefix + "provides_tools:\n" + "".join(f"  - {tool}\n" for tool in tools)
    if suffix_lines:
        rendered += "\n".join(suffix_lines) + "\n"
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=DEFAULT_SOURCE)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    manifest = load_manifest(args.source)
    if manifest.get("schema_version") != 1 or manifest.get("manifest_version") != "1.1.0":
        raise ValueError("unsupported TubeAlfred operation manifest version")
    if manifest.get("operation_count") != len(manifest.get("operations", [])):
        raise ValueError("invalid TubeAlfred operation manifest")

    operations = operations_for(manifest)
    generated = (
        "# This file is generated by scripts/sync_contract.py. Do not edit.\n\n"
        f"MANIFEST_VERSION = {manifest['manifest_version']!r}\n\n"
        f"OPERATIONS = {pprint.pformat(operations, width=100, sort_dicts=False)}\n"
    )
    tools = ["tubealfred_billing_usage", *[operation["name"] for operation in operations]]
    outputs = {
        CONTRACT_PATH: json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        GENERATED_PATH: generated,
        PLUGIN_PATH: render_plugin(tools),
    }

    if args.check:
        stale = [str(path) for path, expected in outputs.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != expected]
        if stale:
            print("generated contract files are stale: " + ", ".join(stale), file=sys.stderr)
            return 1
        print(f"Hermes contract {manifest['manifest_version']} is current.")
        return 0

    for path, value in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(value, encoding="utf-8")
    print(f"Generated {len(operations)} Hermes tools.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
